### ISSUE TITLE
Incorrect map

### ISSUE THREAD

**Issue by mfbx9da4** [tctree333/js-yaml-source-map#9]
The following yaml contents produces an invalid map

```
actions:
  - x-name-override: getById
  - x-name-override: get
  - x-name-override: update
```

it produces the following map

```
.
: 
{line: 1, position: 1, lineStart: 1}
.actions
: 
{line: 2, position: 39, lineStart: 10}
.actions.1
: 
{line: 2, position: 39, lineStart: 10}
.actions.1.x-name-override
: 
{line: 2, position: 39, lineStart: 10}
.actions.2
: 
{line: 3, position: 78, lineStart: 49}
.actions.2.x-name-override
: 
{line: 4, position: 113, lineStart: 84}
.actions.2.yId
: 
{line: 3, position: 78, lineStart: 49}
.actions.2.yId.x-name-override
: 
{line: 3, position: 78, lineStart: 49}
```
